apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trivy-operator-newrelic-agent.fullname" . }}
  labels:
    {{- include "trivy-operator-newrelic-agent.labels" . | nindent 4 }}
type: Opaque
data:
  newRelicApiKey: {{ .Values.newRelic.apiKey | b64enc | quote }}
  newRelicIngestKey: {{ .Values.newRelic.ingestKey | b64enc | quote }}