name: 'CI'

run-name: '0.0.${{ github.run_number }} - ${{ github.workflow }}'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: write
      id-token: write
    uses: mars-office/.github/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      version: '0.0.${{ github.run_number }}'
      updateUmbrellaChartDisabled: true
